baseurl = "https://example.org/"
languageCode = "en-us"
title = "JohnL"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"

[params]
    site_author = "JohnL"
    site_description = "Blow your $."
    location = "San Francisco - Earth"
    # Link custom assets relative to /static
    avatar = "images/IMG_2713.jpeg"
    header_background = "images/IMG_2778.jpeg"
    header_title = "JohnL - Spend Frivolously"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Define which content types are shown on the homepage
    mainSections = ["post"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "bigfootelvis"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "lundberg68"
    gplus     = ""
